language: c
os: linux
dist: focal
services:
  - docker

# Don't build the update-dependencies-pr branch; it's redundant
# with the PR builds that Travis also does.
branches:
  except:
    - /^update-dependencies-pr/

cache:
  directories:
    - ${HOME}/buildx-cache/

# travis login --pro -X --github-token {token}
# travis encrypt --pro {VAR_NAME}={VALUE} -r minikie/manylinux

env:
  global:
    # QUAY_USERNAME and QUAY_PASSWORD for docker image upload
    - secure: "gtIdvmHRvM1KALuFPsfH8h6K7V/sRU2dVzckd0wlbE27UcSTiaRKxWIvSXMEmabmjakrCIniOdPcUq9vNQCtTUh0ipWYQzW8xX6gk/4tjWzFiAnyWoEyBq3SU7vFH43+PaosiK9QRnMniTylMvyhkBhpS2scGEZodSwGVMxBjSexXb8oyq2SGzgfzkTTYqwKwrErAoas7x/DIJx2JRlAHHgSgh6dScK2QmsWt2awsigTpwPhe4UCTSNa92qcruSzWLpL0jVUGafLt4Ct3NEvmSOUA70GYwOHw4GmiaNg4a+rgA+zt5uFdqOej62kzmB5LH5fbWjsbkHIfgBc7E3Ht+rb6otAhx9P5cHWu8TpCehB8Dc8y8gmFovKKHRT+mUVYw6fGRQqHkw6ut9vm1EwMUiq1w4KbVgAAe5R313X7ChEtIMepnf7FPEBQrI9aIOtW7BhWrNRaG7JUwnVnjxpSkl6ZRQEcZhmt9AbysdfmOajbRGrgy+/VnUrIUnZpcQP34qL9BJgU+0CPJxT0UyAAINFPcG4mC7Frf1B2y3RP8xOBtRy+M6Fvp4CbL23uoVb15ty8jrbznwG/vtwXQhr6UEd07HdTmi1f1ToY3zkQgYDl1nmDgrGihMxW1ak5IvQqpseHi6ilx0VG1CNt20wnQKZ+dPcwCpA00yM4+wSO9g="
    - secure: "PnlDT5H/ZWK3HRQ5DuhVQZixTQslUDAV380/AObayi0QUQshZuzwe9eJbfAd9zZX0jAyouhn/Ea2+WMlFbPN9Y+tXPsxTRLo6WlYsvcnhUY/epSfFyn7Th962KGDkk7obQOMqPlPM0coKZqBj9N+Ld+FzxoANYuUXY4bU87YmJTbbAOmkttDlh900a5gNVY22QQs27YjojOFyTIZJPeNb2DwsC2t6Sg6w33pzR4zUxZkohARvwdeJRE3YPEuxxGW/gHuzookwFA+TjL57Dv/FUs4SZHLZclc03mGjNI6dRncGl0CZsG3krEoRRXr1ckc+qzLDiiXp0q9xnQm3idOgZaACCdbw7M6D9cbWdfXnfTNhro9kDWHH3pOAMM9pnW57xqpubLeYFuJzAemOQ/hjmdSH4jjYdD5mb0uEiRznQnP7IsawCCutfg2Tyutm1rHf3SDifIUfirWAW+Oef9WTe9PhzShti1mv3sPEPnfh9A9aBLxMBHMs8VtVC5shpyTuqYLnbln2Gzx03jUd62eRsV6iw2gfdq9eXPCJ1YHsabhrl2JeXDk1xHoSA7OZND5x+6oLg8ZjsLW9I07rrH8W5Kgo0uiuNviMT24MsBlgmwKlBOv8+uOjbBxpWU7uZ3kswDmD0DKI7lPah5olBiuE4rfC0+DEYdP3aPjivam8DY="

jobs:
   include:
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: POLICY="manylinux2014" PLATFORM="aarch64"
    - arch: s390x
      env: POLICY="manylinux2014" PLATFORM="s390x"
    - arch: ppc64le
      env: POLICY="manylinux2014" PLATFORM="ppc64le"
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: POLICY="manylinux_2_28" PLATFORM="aarch64"
    - arch: s390x
      env: POLICY="manylinux_2_28" PLATFORM="s390x"
    - arch: ppc64le
      env: POLICY="manylinux_2_28" PLATFORM="ppc64le"
    - arch: arm64-graviton2
      virt: vm
      group: edge
      env: POLICY="musllinux_1_1" PLATFORM="aarch64"
    - arch: s390x
      env: POLICY="musllinux_1_1" PLATFORM="s390x"
    - arch: ppc64le
      env: POLICY="musllinux_1_1" PLATFORM="ppc64le"

before_install:
  - if [ -d "${HOME}/buildx-cache/.buildx-cache-${POLICY}_${PLATFORM}" ]; then cp -rlf ${HOME}/buildx-cache/.buildx-cache-${POLICY}_${PLATFORM} ./; fi

install:
  - uptime
  - nproc
  - free
  - cat /proc/cpuinfo
  - ./travisci-install-buildx.sh

script: |
  (while true; do echo "travis_wait"; docker stats --no-stream; free; df -h; sleep 30; done) &
  WAIT_PID=$!
  COMMIT_SHA=${TRAVIS_COMMIT} ./build.sh
  kill -9 ${WAIT_PID}
  if [ -d "${HOME}/buildx-cache" ]; then
    rm -rf ${HOME}/buildx-cache
  fi
  mkdir ${HOME}/buildx-cache
  if [ "${MANYLINUX_BUILD_FRONTEND}" != "docker" ]; then
    cp -rlf ./.buildx-cache-* ${HOME}/buildx-cache/
  fi

deploy:
  provider: script
  script: COMMIT_SHA=${TRAVIS_COMMIT} ./deploy.sh
  on:
    branch: main
    repo: pypa/manylinux

after_script:
  - if [ -f ${HOME}/dockerd-rootless.pid ]; then kill -15 $(cat ${HOME}/dockerd-rootless.pid); fi
  - if [ -f /tmp/buildkitd.pid ]; then sudo kill -15 $(cat /tmp/buildkitd.pid); fi
